# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_dist <- function(olat1, olon1, olat2, olon2) {
    .Call(`_whichWithin_haversine_dist`, olat1, olon1, olat2, olon2)
}

do_which_within <- function(lat, lon, r) {
    .Call(`_whichWithin_do_which_within`, lat, lon, r)
}

engrid <- function(x, y, r, xmin = 1, xmax = -1, ymin = 1, ymax = -1, nThread = 1L) {
    .Call(`_whichWithin_engrid`, x, y, r, xmin, xmax, ymin, ymax, nThread)
}

do_minmax <- function(x, y, nThread = 1L) {
    .Call(`_whichWithin_do_minmax`, x, y, nThread)
}

