# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_GG_RES <- function() {
    .Call(`_whichWithin_get_GG_RES`)
}

test_sum_identities <- function(k = 50L, j = 2L, N = 100L) {
    .Call(`_whichWithin_test_sum_identities`, k, j, N)
}

Z4 <- function(x, y) {
    .Call(`_whichWithin_Z4`, x, y)
}

Z4P <- function(x, y, nThread = 1L) {
    .Call(`_whichWithin_Z4P`, x, y, nThread)
}

haversine_dist <- function(olat1, olon1, olat2, olon2) {
    .Call(`_whichWithin_haversine_dist`, olat1, olon1, olat2, olon2)
}

haversine_dist_uys <- function(olat1, olon1, olat2, olon2) {
    .Call(`_whichWithin_haversine_dist_uys`, olat1, olon1, olat2, olon2)
}

haversine_dist_klatlon <- function(lat1, lon1, lat2, lon2, coslat1) {
    .Call(`_whichWithin_haversine_dist_klatlon`, lat1, lon1, lat2, lon2, coslat1)
}

engrid_1D <- function(x, r, xmin, Rx) {
    .Call(`_whichWithin_engrid_1D`, x, r, xmin, Rx)
}

do_which_within <- function(lat, lon, r, lambda0, incl_distance = FALSE) {
    .Call(`_whichWithin_do_which_within`, lat, lon, r, lambda0, incl_distance)
}

do_which_within_within_1km <- function(lat, lon) {
    .Call(`_whichWithin_do_which_within_within_1km`, lat, lon)
}

do_is_within <- function(lat, lon, r, debug = FALSE) {
    .Call(`_whichWithin_do_is_within`, lat, lon, r, debug)
}

is_within_pixels <- function(lat, lon, r, lambda0) {
    .Call(`_whichWithin_is_within_pixels`, lat, lon, r, lambda0)
}

do_locate_in_sorted <- function(xi, y) {
    .Call(`_whichWithin_do_locate_in_sorted`, xi, y)
}

all_in_sorted <- function(x, tbl) {
    .Call(`_whichWithin_all_in_sorted`, x, tbl)
}

engrid <- function(x, y, r, xmin = 1, xmax = -1, ymin = 1, ymax = -1) {
    .Call(`_whichWithin_engrid`, x, y, r, xmin, xmax, ymin, ymax)
}

high_prec_int <- function(x) {
    .Call(`_whichWithin_high_prec_int`, x)
}

interleave_sorted <- function(x, y) {
    .Call(`_whichWithin_interleave_sorted`, x, y)
}

unique_sorted <- function(x) {
    .Call(`_whichWithin_unique_sorted`, x)
}

unique_sorted_inplace <- function(x) {
    .Call(`_whichWithin_unique_sorted_inplace`, x)
}

is_sorted2 <- function(x, y, s2) {
    .Call(`_whichWithin_is_sorted2`, x, y, s2)
}

do_minmax <- function(x, y) {
    .Call(`_whichWithin_do_minmax`, x, y)
}

first_non_na_dbl <- function(x, fill = 0) {
    .Call(`_whichWithin_first_non_na_dbl`, x, fill)
}

Sinusoidal <- function(lat, lon, lambda0 = NA_real_) {
    .Call(`_whichWithin_Sinusoidal`, lat, lon, lambda0)
}

dist_sinusoidal <- function(lat1, lon1, lat2, lon2, lambda0 = NA_real_) {
    .Call(`_whichWithin_dist_sinusoidal`, lat1, lon1, lat2, lon2, lambda0)
}

